# -*- coding: utf-8 -*-
"""prime2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIsI7O6QlJfBfJP4WsOtFaXlUZZeP32l
"""

prime_list = []
c = 0
for i in range(2, 101):
  for j in range(2, i):
    if i % j == 0:
      c = False
      break
    else:
      c = True
  if c :
    prime_list.append(i)
print(prime_list)